#!/bin/sh
set -eu

lb config \
	--distribution trixie \
	--architectures amd64 \
	--binary-images iso-hybrid \
	--debian-installer false \
	--archive-areas "main contrib non-free-firmware" \
	--apt-indices false \
	--memtest none
